# Generated by Django 3.2.23 on 2026-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_leakedsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='validated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='validation_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('not_validated', 'Not validated'), ('confirmed', 'Confirmed'), ('false_positive', 'False positive'), ('needs_review', 'Needs review'), ('error', 'Validation error')], default='not_validated', max_length=20, null=True),
        ),
    ]
