# Generated by Django 3.2.23 on 2026-06-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
        ('startScan', '0004_auto_20260618_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('bucket', models.CharField(blank=True, choices=[('malicious', 'Malicious / Blacklisted'), ('code_repos', 'Public Code Repositories'), ('infra_dns', 'DNS & Email Posture'), ('netblock_asn', 'Netblock / ASN'), ('affiliates', 'Affiliates'), ('cohosted', 'Co-Hosted Sites'), ('geo', 'Geolocation'), ('web_tech', 'Web Technology'), ('other', 'Other')], max_length=50, null=True)),
                ('event_type', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=2000, null=True)),
                ('extra', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('severity', models.IntegerField(default=0)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
    ]
