# Generated by Django 3.2.23 on 2026-06-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_osintresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintresult',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintresult',
            name='module',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='osintresult',
            name='parent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='osintresult',
            name='bucket',
            field=models.CharField(blank=True, choices=[('malicious', 'Malicious / Blacklisted'), ('code_repos', 'Public Code Repositories'), ('infra_dns', 'DNS & Email Posture'), ('netblock_asn', 'Netblock / ASN'), ('affiliates', 'Affiliates'), ('cohosted', 'Co-Hosted Sites'), ('geo', 'Geolocation'), ('web_tech', 'Web Technology'), ('organization', 'Organization / Identity'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
