# Generated by Django 3.2.23 on 2026-06-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_gitguardianapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('key_enc', models.TextField()),
                ('extra_enc', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
