# Generated by Django 3.2.23 on 2026-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_hackerone_send_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, default='Suricatoos', max_length=100)),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Branding Setting',
            },
        ),
    ]
