# Generated by Django 3.2.23 on 2026-06-18 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_brandingsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsetting',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'ico'])]),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='logo_dark',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='logo_light',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
    ]
